---
- name: Install IIS Web Server
  win_feature:
    name: Web-Server
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes

- name: Restart IIS service
  win_service:
    name: W3SVC
    state: restarted


- name: Wait for the IIS service to start and listen on http port
  win_wait_for:
    host: "{{ ansible_host }}"
    port: "{{ http_port }}"
    timeout: 300
    delay: 5

- name: Send some HTTP requests to create IIS logs
  win_uri:
    url: "{{ url }}"
    method: GET
    return_content: yes
  loop: "{{ range(1, 11) | list }}"
  delay: 1
...